// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enabled': string;
  'features': string;
  'metadataProvider': string;
  'name': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
