// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addMetadataProvider': string;
  'center': string;
  'metadataProviders': string;
}
export const cssExports: CssExports;
export default cssExports;
